version: "3"

services:
  app:
    image: app
    container_name: steroidPHP-app
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: steroidPHP-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: steroidphp
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Prep for the future
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:8080"]
  #   interval: 10s
  #   timeout: 5s
  #   retries: 3

volumes:
  mysql_data:
