version: "3"

services:
  app:
    image: app
    container_name: steroidPHP-app
    build: .
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: steroidPHP-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: steroidphp
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    container_name: steroidPHP-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-app

volumes:
  mysql_data:
