version: "3"

services:
  php-app:
    image: app
    container_name: phpplayground-app
    build: .
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: phpplayground-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: phpmyadmin
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpplayground-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
    ports:
      - "8082:80"
    depends_on:
      - mysql

  nginx:
    container_name: phpplayground-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-app

volumes:
  mysql_data:
